# Generated by Django 5.2.5 on 2025-08-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_personrole_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_role', to='movies.person'),
        ),
    ]
