# Generated by Django 5.2.5 on 2025-08-14 05:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_personrole_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_backdrops/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_role', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='webshow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webshow_role', to='movies.webshow'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='webshow',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='show_backdrops/'),
        ),
        migrations.AlterField(
            model_name='webshow',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='show_posters/'),
        ),
    ]
