# Generated by Django 5.2.5 on 2025-08-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_cast_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(default='Not streaming.', max_length=100),
        ),
    ]
