# Generated by Django 5.2.5 on 2025-08-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='streaming_platform',
            field=models.ManyToManyField(default='Not streaming.', to='movies.platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
