# Generated by Django 5.2.5 on 2025-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_streaming_platform_alter_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='streaming_platform',
            field=models.ManyToManyField(blank=True, default='Not streaming.', null=True, to='movies.platform'),
        ),
    ]
