# Generated by Django 5.2.5 on 2025-08-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_streaming_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webshow',
            old_name='number_of_season',
            new_name='seasons_count',
        ),
    ]
