# Generated by Django 5.2.5 on 2025-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_number_of_season_webshow_seasons_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/'),
        ),
    ]
