# Generated by Django 5.2.5 on 2025-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_episode_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='webshow_media/episode_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_media/movie_backdrops/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_media/movie_posters/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='person_media/person_profiles/'),
        ),
        migrations.AlterField(
            model_name='webseason',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='webshow_media/season_posters/'),
        ),
        migrations.AlterField(
            model_name='webshow',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='webshow_media/show_backdrops/'),
        ),
        migrations.AlterField(
            model_name='webshow',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='webshow_media/show_posters/'),
        ),
    ]
