# Generated by Django 5.2.5 on 2025-08-29 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('movies', '0011_reviewlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='review_user',
        ),
        migrations.RenameField(
            model_name='reviewlike',
            old_name='user',
            new_name='like_user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('review_user', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('like_user', 'review')},
        ),
    ]
