# Generated by Django 5.2.5 on 2025-09-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_award_boxoffice_fantheory_galleryimage_movietrivia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Backdrop_image',
            new_name='backdrop_image',
        ),
    ]
