# Generated by Django 5.2.5 on 2025-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_backdrop_image_movie_backdrop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='movie_media/person_profiles/'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_media/platform_logos/'),
        ),
    ]
