# Generated by Django 5.2.5 on 2025-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_person_profile_pic_alter_platform_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantheory',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
