# Generated by Django 5.2.5 on 2025-09-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_fantheory_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantheory',
            name='points',
        ),
        migrations.CreateModel(
            name='FanTheoryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.fantheory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('theory', 'user')},
            },
        ),
    ]
