# Generated by Django 5.2.5 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantheory',
            name='theory',
            field=models.TextField(max_length=50),
        ),
    ]
