# Generated by Django 5.2.5 on 2025-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_fantheory_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantheory',
            name='theory',
            field=models.TextField(max_length=200),
        ),
    ]
